### ISSUE TITLE
Broken SDK, Issue when getting supportedBanks

### ISSUE THREAD

**Issue by Perjan** [figo-connect/ios-sdk#1]
Hey guys, thanks for the amazing SDK.
Unfortunately I found a bug :(

Currently I am calling the retrieveSupportedBanks and as a response I am getting a failure back.
It says:
[Unbox error] Invalid value **< the entire json output. A lot of banks here>** for key banks

Can you please check into this?

Thanks,
Perjan

**Comment by CodeStage** [comment]
Thanks for your feedback, we will look into it.

**Comment by Perjan** [comment]
Thanks Christian, please take a look as something may be corrupt from the JSON coming from the API, as the SDK code looked fine to me. Maybe some of the SupportedBank properties should be Optional...

Please let me know as my development is frozen.

Have an amazing weekend (after fixing the bug, of course :) ).
Cheers,
Perjan

**Comment by Perjan** [comment]
Hey guys, any news?

**Comment by CodeStage** [comment]
I've created a pull request with the fix
