### ISSUE TITLE
Cannot Login with Demo Account

### ISSUE THREAD

**Issue by Perjan** [figo-connect/ios-sdk#13]
I am trying to login with the demo account, but it can't.
Two weeks ago it was fine. I didn't change anything from my side...

It is throwing an error which says "Abgebrochen".

<img width="458" alt="screenshot 2017-06-30 14 36 32" src="https://user-images.githubusercontent.com/2928568/27735846-d6334e92-5da1-11e7-86ac-52f6a5bb3612.png">

**Comment by Perjan** [comment]
@CodeStage Found it. This doesn't work on the master branch, but if I switch to cert-update, it works perfectly. I am guessing this has something to do with the new certificates.

**Comment by CodeStage** [comment]
Yes, we have crated a new release that contains the new certificates.
