### ISSUE TITLE
Problems when retrieving transactions

### ISSUE THREAD

**Issue by mmxme** [figo-connect/ios-sdk#3]
Hi, I had the following issue:

When I tried to retrieve transactions using the figo-swift-sdk I got an unboxing error.

`
figo.retrieveTransactionsForAccount(account.accountId!, parameters: parameters) { result in
            switch result {
            case .Success(let envelope):
                print("Retrieved \(envelope.transactions.count) transactions")
                break
            case .Failure(let error):
                print(error)
                break
            }
        }
    }
` 

I found a workaround by making the changes show in the attached screenshot.
![figo-ios-sdk__git_](https://cloud.githubusercontent.com/assets/1071618/16227077/eb94da68-37ae-11e6-87d4-51c8e5c553c4.png)

The API seems to send PaymentTypes, which are not defined in the Enum PaymentType

`
public enum PaymentType: String, UnboxableEnum {
    case Unknown
    case Transfer
    case DirectDebit = "Direct debit"
    case SEPATransfer = "SEPA transfer"
    case SEPADirectDebit = "SEPA direct debit"
    case Interest = "interest"
    case Charges
    case ATM
    case GeldKarte
    case Rent = "rent"
    case StandingOrder = "Standing order"
    case ElectronicCash = "Electronic cash"
    case SEPAStandingOrder = "SEPA standing order"
    case ModifySEPAStandingOrder = "Modify SEPA standing order"

```
static func unboxFallbackValue() -> PaymentType {
    return .Unknown
}   
```

}`

The function unboxFallbackValue() didn't work for me.

**Comment by CodeStage** [comment]
Thanks for your feedback, we're working on it.

**Comment by CodeStage** [comment]
We have resolved this issue.
