### ISSUE TITLE
Error when retrieving transactions

### ISSUE THREAD

**Issue by henrikengelbrink** [figo-connect/ios-sdk#4]
Hello, 

I've two problems when retrieving the transactions from an account.

First Problem: I want to set the parameters, but Xcode gives the following error when creating the parameters like this:`var params = RetrieveTransactionsParameters()` 
Warning: RetrieveTransactionsParameters cannot be constructed because it has no accessible initializers

Second Problem:
If load the transactions with the default parameters it is not successful, I get the following result: 
`FAILURE: [Unbox error] Invalid value ((
        {
        "account_id" = "XXX";
        "account_number" = XXX;
        amount = "-XXX";
        "bank_code" = XXX;
        "bank_name" = "XXX";
        booked = XXX;
        "booking_date" = "XXX";
        "booking_text" = "XXX";
        "creation_timestamp" = "XXX";
        currency = EUR;
        "modification_timestamp" = "XXX";
        name = "XXX";
        purpose = "XXX";
        "transaction_code" = 5;
        "transaction_id" = "XXX";
        type = "XXX";
        "value_date" = "XXX";
        visited = 0;
    },
        {
         ...
    },
        {
        ...
    }
)) for key (transactions)`

I hope somebody can help with this problems.

**Comment by Perjan** [comment]
I have the same problem. It has been like this for the last 4 months. Guys, please fix this

**Comment by CodeStage** [comment]
As for your first problem, I could not reproduce that in a demo project. Please let us know if you're still running into that.

We have fixed a couple of things related to transactions. Please try again and let us know if you still have problems.
