### ISSUE TITLE
[Question] swift3 support

### ISSUE THREAD

**Issue by pteasima** [figo-connect/ios-sdk#5]
Hi, we are thinking about using this SDK in our application. Is this project still alive? Will it be ready for swift3 when it comes out of beta in the fall?

**Comment by lad1337** [comment]
it's alive, changes / compatibility with switft3 we have to evaluate

**Comment by Perjan** [comment]
Guys, when will you release the Swift 3 version?
It is blocking one of our apps and we don't want to switch to other SDKs just because of Swift 3 support.

Thanks

**Comment by CodeStage** [comment]
We have updated the project to support Swift 3
