### ISSUE TITLE
Crash trying to force unwrap refresh token

### ISSUE THREAD

**Issue by pteasima** [figo-connect/ios-sdk#6]
When I login using the method 

```
figo.loginWithUsername("username", password: "password", clientID: "clientId", clientSecret: "clientSecret"
```

the app crashes at AuthorizationEndpoints.swift line:37 trying to force unwrap the refreshToken, which is nil. I've edited the code to return the access token instead

```
//...
completionHandler(Result.Success(authorization.accessToken))
//...
```

and all seems to work fine.

Please let me know if you will be actively developing the sdk in the future and fixing these issues. We are currently in prototyping stage, so we are ok with integrating the figo ios sdk sourcecode directly and fixing some issues. However, we need to see some promise in figo before using it for a production app. Even the basic example `let figo = FigoClient()` from your readme doesnt compile, which makes this whole sdk look questionable.

**Comment by CodeStage** [comment]
I tried reproducing your issue(s) and failed. If you still have problems, please open another issue.
