### ISSUE TITLE
Error on retrieveTransactions from Demo Account

### ISSUE THREAD

**Issue by Perjan** [figo-connect/ios-sdk#9]
Hi, I am getting this error when retrieving the transactions from the demo account.
The method used is :
```swift
func retrieveTransactions(_ parameters: RetrieveTransactionsParameters = RetrieveTransactionsParameters(), _ completionHandler: @escaping (FigoResult<TransactionListEnvelope>) -> Void)
```

> [UnboxError] An error occured while unboxing path "value_date": Invalid value (<null>) for key "value_date".

**Comment by CodeStage** [comment]
Thanks for your feedback, can you update and try again?

**Comment by Perjan** [comment]
Perfect, thanks Christian.
